apiVersion: v1
kind: Service
metadata:
  name: deepqa
  labels:
    app: deepqa
    role: master
    tier: backend
spec:
  ports:
    - port: 8000 
      targetPort: 8000
  # Replace with the IP of your minikube node / master node if you want external access
  externalIPs:
    - 192.168.99.101
  selector:
    app: deepqa 
    role: master
    tier: backend
